update

diff --git a/home/.local/bin/debian-stack b/home/.local/bin/debian-stack
--- a/home/.local/bin/debian-stack
+++ b/home/.local/bin/debian-stack
@@ -1,15 +1,16 @@
 #!/bin/bash
 
 #
-# Save this as $HOME/.local/bin/debian-stack and then make sure 
-# $HOME/.local/bin is in your path.  This will allow you to use
-# the command `debian-stack` any where you would have previously
-# used the `stack` command.
+# Save this on your $PATH for example in $HOME/.local/bin. This
+# will allow you to use the command `debian-stack` any where you
+# would have previously used the `stack` command.
 # 
 
 if [[ ! -f stack.yaml ]]; then
-  echo "Can't find a stack.yaml file.  Cowardly aborting."
-  exit
+  echo ""
+  echo "Can't find a stack.yaml file.  The current directory doesn't appear to be a Haskell Stack project.  Cowardly aborting."
+  echo ""
+  exit 1
 fi
 
 #
@@ -18,21 +19,30 @@ fi
 docker pull mgreenly/debian-stack:latest
 
 #
-# the .debian-stack directory is mapped into the debian-stack
-# image as the global $HOME/.stack directory so that it doesn't
-# have to rebuild everything from scratch every time you run
-# it for the project.
+# Docker doesn't allow build contexts to include directories
+# outside the current working directory.  So this script links
+# the current users $HOME/.stack.debian directory into the
+# working project directory if necessary and then mounts
+# that directory as $HOME/.stack inside the container
 #
-# Docker doesn't allow acess to directories outside the current
-# project so there's no practical way to share the stack global
-# directory between projects
+# This allows stack to reuse compiled packages between projects
+# like it normally would when not run in a container.
 #
-mkdir -p $PWD/.debian-stack
+if [[ ! -e $HOME/.stack.debian ]]; then
+  mkdir $HOME/.stack.debian
+fi
+
+if [[ ! -d .stack.debian ]]; then
+  ln -s $HOME/.stack.debian $PWD/.stack.debian
+  exit
+fi
 
 #
-# all arguments given to this script are passed to stack running in the image
+# all arguments given to this script are passed to the stack application
+# running in the container
 #
 docker run --rm -i -t \
-  -v $PWD/.debian-stack:/home/haskell/.stack  \
-  -v $PWD:/data \
-  mgreenly/debian-stack:latest stack $@
+  -v $PWD/.stack.debian:/home/haskell/.stack  \
+  -v $PWD:/project \
+  mgreenly/debian-stack:latest \
+  stack $@
