update local/bin

diff --git a/home/.local/bin/stack-new b/home/.local/bin/stack-new
--- a/home/.local/bin/stack-new
+++ b/home/.local/bin/stack-new
@@ -4,8 +4,8 @@
 # TODO: figure out how to turn this into a stack template
 #
 
-if [ "$#" -ne 1 ]; then
-  echo "usage: stack-new NAME"
+if [ "$#" -ne 2 ]; then
+  echo "usage: stack-new [app|lib] NAME"
   echo ""
   echo "  NAME - a lower case hyphenated package name"
   echo ""
@@ -13,7 +13,11 @@ if [ "$#" -ne 1 ]; then
 fi
 
 # the package name is hyphenated lower case
-PACKAGE_NAME=${1,,}
+PACKAGE_TYPE=${1,,}
+
+# the package name is hyphenated lower case
+PACKAGE_NAME=${2,,}
+
 
 # The module name is upper camel cased.  This mess
 # splits the package name on hyphens, then appends
@@ -38,14 +42,19 @@ if [[ -e $PACKAGE_NAME ]]; then
 fi
 mkdir $PACKAGE_NAME
 cd $PACKAGE_NAME
-mkdir "src" "app" "test"
 
+mkdir "src" "test"
+
+
+case $PACKAGE_TYPE in
+  lib)
 #
 # create the cabal file
 #
 cat << EOF > $PACKAGE_NAME.cabal
 name:                  $PACKAGE_NAME
 version:               0.0.1
+synopsis:              Auto generated synopsis for $PACKAGE_NAME package
 homepage:              https://github.com/$USER
 license:               ISC
 license-file:          LICENSE
@@ -54,41 +63,79 @@ maintainer:            ${USER_EMAIL}
 build-type:            Simple
 cabal-version:         >=1.10
 
+source-repository head
+  type:               git
+  location:           https://github.com/$USER/$PACKAGE_NAME
+
 library
   default-language:    Haskell2010
   hs-source-dirs:      src
   exposed-modules:     $MODULE_NAME
   ghc-options:         -O2
                        -threaded
-                       "-with-rtsopts=-N"
+                       -with-rtsopts=-N
+                       -static
+                       -optc-static
+                       -optl-static
+                       -optl-pthread
   build-depends:       base                    >= 4.8
-
-
-executable $PACKAGE_NAME-app
-  default-language:    Haskell2010
-  hs-source-dirs:      app
-  main-is:             Main.hs
-  ghc-options:         -O2
-                       -threaded
-                       "-with-rtsopts=-N"
-  build-depends:       base                    >= 4.8
-                       , $PACKAGE_NAME
 
 test-suite $PACKAGE_NAME-test
   type:                exitcode-stdio-1.0
   default-language:    Haskell2010
   hs-source-dirs:      test
-  main-is:             Spec.hs
+                       , src
+  main-is:             Test.hs
   build-depends:       base
-                       , $PACKAGE_NAME
                        , hspec
                        , QuickCheck
+EOF
+;;
+  app)
+#
+# create the cabal file
+#
+cat << EOF > $PACKAGE_NAME.cabal
+name:                  $PACKAGE_NAME
+version:               0.0.1
+synopsis:              Auto generated synopsis for $PACKAGE_NAME package
+homepage:              https://github.com/$USER
+license:               ISC
+license-file:          LICENSE
+author:                ${USER_NAME}
+maintainer:            ${USER_EMAIL}
+build-type:            Simple
+cabal-version:         >=1.10
 
 source-repository head
   type:               git
   location:           https://github.com/$USER/$PACKAGE_NAME
-EOF
 
+executable             $PACKAGE_NAME
+  default-language:    Haskell2010
+  hs-source-dirs:      src
+  main-is:             Main.hs
+  other-modules:       Foo
+  ghc-options:         -O2
+                       -threaded
+                       "-with-rtsopts=-N"
+  build-depends:       base                    >= 4.8
+
+test-suite $PACKAGE_NAME-test
+  type:                exitcode-stdio-1.0
+  default-language:    Haskell2010
+  hs-source-dirs:      test
+                       , src
+  main-is:             Test.hs
+  build-depends:       base
+                       , hspec
+                       , QuickCheck
+EOF
+;;
+*)
+  echo "unknown package type"
+  exit
+esac
 
 
 #
@@ -116,14 +163,20 @@ EOF
 # create a project specific .vimrc file
 #
 cat << EOF > .vimrc
+"" build project with profiling
+map <leader>p :exe '!clear && stack build --executable-profiling --library-profiling --ghc-options="-rtsopts"'<CR>
+map <leader>P :exe '!clear && stack exec $PACKAGE_NAME -- +RTS -sstderr'<CR>
+"" build for threadscope with eventlog
+map <leader>e :exe '!clear && stack build --ghc-options="-eventlog -rtsopts"'<CR>
+map <leader>E :exe '!clear && stack exec $PACKAGE_NAME -- +RTS -N2 -l'<CR>
 "" build - build project
-map <leader>b :exe '!clear && stack build'<CR>
+map <leader>b :exe '!clear && stack build --pedantic'<CR>
 "" clean - clean build artifacts
 map <leader>c :exe '!clear && stack clean'<CR>
 "" interactive - load modules in repl
 map <leader>i :exe '!clear && stack ghci'<CR>
 "" run - run program
-map <leader>r :exe '!clear && stack build && clear && stack exec $PACKAGE_NAME-app'<CR>
+map <leader>r :exe '!clear && stack build && clear && stack exec $PACKAGE_NAME'<CR>
 "" spec - run specs
 map <leader>s :exe '!clear && stack test'<CR>
 "" spec - run specs
@@ -174,21 +227,25 @@ EOF
 # create a gitignore file
 #
 cat << EOF > .gitignore
-/.cabal-sandbox
-/client_session_key.aes
-/dist
-/tags
-/TAGS
+/*.deb
 /*.hp
 /*.prof
-.DS_Store
-.*.sw?
-.stack-work
+/.*.sw?
+/.DS_Store
+/.cabal-sandbox
+/.stack-work
+/client_session_key.aes
+/dist
+/pkg-debian
+/tags
+/TAGS
 EOF
 
 #
 # create sample source files
 #
+case $PACKAGE_TYPE in
+  lib)
 cat << EOF > src/$MODULE_NAME.hs
 module $MODULE_NAME
     ( foo
@@ -197,27 +254,51 @@ module $MODULE_NAME
 foo :: String
 foo = "foo"
 EOF
+    ;;
+  app)
+cat << EOF > src/Foo.hs
+module Foo
+    ( foo
+    ) where
+
+foo :: String
+foo = "foo"
+EOF
+    ;;
+  *)
+    echo "error, uknown package type"
+    exit 1
+esac
 
 #
 # create application
 #
-cat << EOF > app/Main.hs 
+if [[ $PACKAGE_TYPE == 'app' ]]; then
+cat << EOF > src/Main.hs
 module Main where
 
-import $MODULE_NAME (foo)
+import Foo (foo)
 
+main :: IO ()
 main = putStrLn foo
 EOF
+fi
+
+if [[ $PACKAGE_TYPE == 'app' ]]; then
+TEST_MODULE_NAME="Foo"
+else
+TEST_MODULE_NAME=$MODULE_NAME
+fi
 
 #
 # create application
 #
-cat << EOF > test/Spec.hs 
+cat << EOF > test/Test.hs
 import Test.Hspec
 import Test.QuickCheck
 import Control.Exception (evaluate)
 
-import $MODULE_NAME
+import $TEST_MODULE_NAME
 
 main :: IO ()
 main = hspec $ do
@@ -226,3 +307,5 @@ main = hspec $ do
         it "foo returns the expected value" $ do
             foo \`shouldBe\` ("foo" :: String)
 EOF
+
+stack init
